testing changes

diff --git a/jenkins-pipelines/Jenkinsfile b/jenkins-pipelines/Jenkinsfile
--- a/jenkins-pipelines/Jenkinsfile
+++ b/jenkins-pipelines/Jenkinsfile
@@ -1,4 +1,4 @@
-// //WORK IN PROGRESS//
+// //WORK IN PROGRESS/ jenkinsfile
 pipeline {
   agent {
     dockerfile {
@@ -13,8 +13,7 @@ pipeline {
     buildDiscarder(logRotator(numToKeepStr: '5'))
   }
 
-  environment {
-    TEST_API_KEY='Wfose208FveQAeosYHkZ5w'
+  environment {    
     CODEBASE = 'flirconservator-cli'
   }
   
@@ -73,7 +72,54 @@ pipeline {
               def test = build job: 'Flirconservator+CLI_Integration_Testing', parameters: [string(name: 'IMAGE_TYPE', value: 'LOCAL'), string(name: 'LOCAL_BRANCH', value: 'master')]
             }
           }
-        }        
+        }
+          stage("Documentation Tests") {
+          steps {
+            echo "Building docs..."
+            dir("docs") {
+              sh "make html"
+            }
+          }
+        }
+
+        stage("Deploy Documentation") {
+      when {       
+        not { changeRequest() }
+      }
+      steps {
+        echo "Deploying..."
+        // sh "mv docs/_build/html temp/"
+        // sh "git reset --hard"
+        // sh "rm -rf .git/hooks/*"
+        // sh "git checkout gh_pages"
+        // sh "rm -rf docs/"
+        // sh "mv temp/ docs/"
+        // sh "touch docs/.nojekyll"
+        // sh "git add docs/"
+        // sh "git commit -m 'Build docs for ${BUILD_TAG}' || echo 'Commit failed. There is probably nothing to commit.'"
+        // sshagent(credentials: ["flir-service-key"]) {
+        //   sh "git push || echo 'Push failed. There is probably nothing to push.'"
+        // }
+      }
+    }
+    stage("Release on PyPI") {
+      when {
+        buildingTag()
+      }
+      environment {
+        TWINE_REPOSITORY = "pypi"
+        TWINE_USERNAME = "__token__"
+        TWINE_PASSWORD = credentials("pypi-conservator-cli")
+      }
+      steps {
+        sh "python setup.py --version"
+        sh "pip install build twine"
+        sh "python -m build"
+        //check before
+        //sh "python -m twine upload dist/*"
+      }
+    }
+
       }
     }
   }
