testing

diff --git a/jenkins-pipelines/Jenkinsfile b/jenkins-pipelines/Jenkinsfile
--- a/jenkins-pipelines/Jenkinsfile
+++ b/jenkins-pipelines/Jenkinsfile
@@ -69,7 +69,7 @@ pipeline {
           steps {
             script {
               sendNotifications("Merge to main pipeline started")
-              //def test = build job: 'Flirconservator+CLI_Integration_Testing', parameters: [string(name: 'IMAGE_TYPE', value: 'LOCAL'), string(name: 'LOCAL_BRANCH', value: 'master')]
+              def test = build job: 'Flirconservator+CLI_Integration_Testing', parameters: [string(name: 'IMAGE_TYPE', value: 'LOCAL'), string(name: 'LOCAL_BRANCH', value: 'master')]
             }
           }
         }
@@ -100,32 +100,30 @@ pipeline {
       }
       steps {
         echo "Deploying..."
-        // sh "mv docs/_build/html temp/"
-        // sh "git reset --hard"
-        // sh "rm -rf .git/hooks/*"
-        // sh "git checkout gh_pages"
-        // sh "rm -rf docs/"
-        // sh "mv temp/ docs/"
-        // sh "touch docs/.nojekyll"
-        // sh "git add docs/"
-        // sh "git commit -m 'Build docs for ${BUILD_TAG}' || echo 'Commit failed. There is probably nothing to commit.'"
-        // sshagent(credentials: ["flir-service-key"]) {
-        //   sh "git push || echo 'Push failed. There is probably nothing to push.'"
-        // }
+        sh "mv docs/_build/html temp/"
+        sh "git reset --hard"
+        sh "rm -rf .git/hooks/*"
+        sh "git checkout gh_pages"
+        sh "rm -rf docs/"
+        sh "mv temp/ docs/"
+        sh "touch docs/.nojekyll"
+        sh "git add docs/"
+        sh "git commit -m 'Build docs for ${BUILD_TAG}' || echo 'Commit failed. There is probably nothing to commit.'"
+        sshagent(credentials: ["flir-service-key"]) {
+          sh "git push || echo 'Push failed. There is probably nothing to push.'"
+        }
       }
     }
-    stage("Release on PyPI") {
-      //not sure , check with conservator team/
-      //when {
-//        buildingTag()
-      //}
+    stage("Release on PyPI") {       
+      when {
+        buildingTag()
+      }
       environment {
         TWINE_REPOSITORY = "pypi"
         TWINE_USERNAME = "__token__"
         TWINE_PASSWORD = credentials("pypi-conservator-cli")
       }
-      steps {
-        echo "here"
+      steps {        
         sh "echo $TWINE_PASSWORD | base64"
         sh "python setup.py --version"
         sh "pip install build twine"
